### ISSUE TITLE
South app dependency creates errors with Django 1.8

### ISSUE THREAD

**Issue by theaverageguy** [peragro/django-project#4]
The current stackoverflow answers suggest to downgrade Django version to 1.6 or something. 
Can this be tackled? I would say no one would prefer to downgrade Django, so we should think of an alternative.

**Comment by pgudlani** [comment]
Can port to Django 1.9 and start using [django-migrations](https://docs.djangoproject.com/en/1.9/topics/migrations/) instead of south.

**Comment by saganshul** [comment]
agree with @pgudlani . No Need to use south anymore.

**Comment by theaverageguy** [comment]
@pgudlani @saganshul I Would like to fix this.

**Comment by pgudlani** [comment]
@theaverageguy I have done this with my applications. What are you talking about is porting the whole application from django 1.6 to django 1.9
Let me try and do this.

**Comment by kunalsharma05** [comment]
Hey guys, since the current app uses 1.6 I think you should just setup 1.6 in your virtual environment and use south to create migrations by using schemamigration command, i.e, `python manage.py schemamigration django_project --auto` (This was the command for creating migrations before makemigrations was available that is after 1.7) because I think porting a project to a higher version from a version before 1.7 may cause many errors, so to setup the project and get a gist of it you should just use the version it was made in still it's you call. Hope this helps :)

**Comment by pgudlani** [comment]
Porting to a newer version would anyway be better. Also, as now it is not a big project it will be easy to do that

**Comment by kunalsharma05** [comment]
@pgudlani I agree, please do so then, it will be a help to others who wish to setup the project and are new to Django. :)
